### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by queenkoopa8500** [coop-deluxe/website#2]
![Screenshot 2024-03-08 095800](https://github.com/coop-deluxe/website/assets/155935644/10e06da6-92b0-4217-b1fc-5588b93f2769)
I get this error.

**Comment by Dolphin2Point1** [comment]
I had this problem too. It seems the domain for the website expired. Hope this gets fixed soon, nobody can use patcher in the meantime. :/

**Comment by queenkoopa8500** [comment]
> I had this problem too. It seems the domain for the website expired. Hope this gets fixed soon, nobody can use patcher in the meantime. :/

I just found out it expired as the whois dns servers for it now show up as: `ns1.dns-suspended.com` and `ns2.dns-suspended.com`

**Comment by queenkoopa8500** [comment]
> I had this problem too. It seems the domain for the website expired. Hope this gets fixed soon, nobody can use patcher in the meantime. :/

Its back tho https://mods.sm64coopdx.com isnt available now
